// Code generated by MockGen. DO NOT EDIT.
// Source: ./repositoryv1/iface.go

// Package repositoryv1mock is a generated GoMock package.
package repositoryv1mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	proto "github.com/lovemew67/leader-board/gen/go/proto"
	cornerstone "github.com/lovemew67/public-misc/cornerstone"
)

// MockScoreV1Repository is a mock of ScoreV1Repository interface.
type MockScoreV1Repository struct {
	ctrl     *gomock.Controller
	recorder *MockScoreV1RepositoryMockRecorder
}

// MockScoreV1RepositoryMockRecorder is the mock recorder for MockScoreV1Repository.
type MockScoreV1RepositoryMockRecorder struct {
	mock *MockScoreV1Repository
}

// NewMockScoreV1Repository creates a new mock instance.
func NewMockScoreV1Repository(ctrl *gomock.Controller) *MockScoreV1Repository {
	mock := &MockScoreV1Repository{ctrl: ctrl}
	mock.recorder = &MockScoreV1RepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScoreV1Repository) EXPECT() *MockScoreV1RepositoryMockRecorder {
	return m.recorder
}

// CleanScores mocks base method.
func (m *MockScoreV1Repository) CleanScores(arg0 cornerstone.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanScores", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CleanScores indicates an expected call of CleanScores.
func (mr *MockScoreV1RepositoryMockRecorder) CleanScores(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanScores", reflect.TypeOf((*MockScoreV1Repository)(nil).CleanScores), arg0)
}

// InsertScore mocks base method.
func (m *MockScoreV1Repository) InsertScore(arg0 cornerstone.Context, arg1 *proto.ScoreV1) (*proto.ScoreV1, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertScore", arg0, arg1)
	ret0, _ := ret[0].(*proto.ScoreV1)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertScore indicates an expected call of InsertScore.
func (mr *MockScoreV1RepositoryMockRecorder) InsertScore(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertScore", reflect.TypeOf((*MockScoreV1Repository)(nil).InsertScore), arg0, arg1)
}

// ListTopKHighestScores mocks base method.
func (m *MockScoreV1Repository) ListTopKHighestScores(arg0 cornerstone.Context, arg1 int) ([]*proto.ScoreV1, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTopKHighestScores", arg0, arg1)
	ret0, _ := ret[0].([]*proto.ScoreV1)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTopKHighestScores indicates an expected call of ListTopKHighestScores.
func (mr *MockScoreV1RepositoryMockRecorder) ListTopKHighestScores(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTopKHighestScores", reflect.TypeOf((*MockScoreV1Repository)(nil).ListTopKHighestScores), arg0, arg1)
}

// MockScoreV1CacheRepository is a mock of ScoreV1CacheRepository interface.
type MockScoreV1CacheRepository struct {
	ctrl     *gomock.Controller
	recorder *MockScoreV1CacheRepositoryMockRecorder
}

// MockScoreV1CacheRepositoryMockRecorder is the mock recorder for MockScoreV1CacheRepository.
type MockScoreV1CacheRepositoryMockRecorder struct {
	mock *MockScoreV1CacheRepository
}

// NewMockScoreV1CacheRepository creates a new mock instance.
func NewMockScoreV1CacheRepository(ctrl *gomock.Controller) *MockScoreV1CacheRepository {
	mock := &MockScoreV1CacheRepository{ctrl: ctrl}
	mock.recorder = &MockScoreV1CacheRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScoreV1CacheRepository) EXPECT() *MockScoreV1CacheRepositoryMockRecorder {
	return m.recorder
}

// CleanTopKScores mocks base method.
func (m *MockScoreV1CacheRepository) CleanTopKScores(arg0 cornerstone.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanTopKScores", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CleanTopKScores indicates an expected call of CleanTopKScores.
func (mr *MockScoreV1CacheRepositoryMockRecorder) CleanTopKScores(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanTopKScores", reflect.TypeOf((*MockScoreV1CacheRepository)(nil).CleanTopKScores), arg0)
}

// GetTopKScores mocks base method.
func (m *MockScoreV1CacheRepository) GetTopKScores(arg0 cornerstone.Context) ([]*proto.ScoreV1, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopKScores", arg0)
	ret0, _ := ret[0].([]*proto.ScoreV1)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopKScores indicates an expected call of GetTopKScores.
func (mr *MockScoreV1CacheRepositoryMockRecorder) GetTopKScores(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopKScores", reflect.TypeOf((*MockScoreV1CacheRepository)(nil).GetTopKScores), arg0)
}

// SetTopKScores mocks base method.
func (m *MockScoreV1CacheRepository) SetTopKScores(arg0 cornerstone.Context, arg1 []*proto.ScoreV1) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTopKScores", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetTopKScores indicates an expected call of SetTopKScores.
func (mr *MockScoreV1CacheRepositoryMockRecorder) SetTopKScores(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTopKScores", reflect.TypeOf((*MockScoreV1CacheRepository)(nil).SetTopKScores), arg0, arg1)
}
